### ISSUE TITLE
Regarding the evaluation procedure

### ISSUE THREAD

**Issue by alphadoretto** [jerinphilip/fairseq-ilmt#1]

**Comment by jerinphilip** [comment]
It's at the following link:

* https://github.com/jerinphilip/indic_nlp_library/tree/master/indicnlp/contrib/wat

But I suggest you use https://github.com/jerinphilip/wateval instead. It replicates the numbers on the [WAT evaluation website](http://lotus.kuee.kyoto-u.ac.jp/WAT/evaluation/list.php?t=14&o=4), which is pretty standard and reported by a lot of people. 

We address the evaluations quite a bit in our recent Pre-print:
* [Revisiting Low Resource Status of Indian Languages in Machine Translation](https://arxiv.org/abs/2008.04860)

We normally fit the evaluation metrics to the venue it's hosted on (the task/language-pair).

**Comment by jerinphilip** [comment]
One last thing, don't use the generated references - sometimes there is a loss of tokens and disparity in BLEU. Use references from the original test-set. We use this script as a proxy, if numbers are good we shift to the proper evaluations.

**Comment by alphadoretto** [comment]
Right, thanks I will check the pre-print. 

This is just for my convenience to make sure that I have understood what you conveyed in your comment. The ```generate.py``` at this moment apart from ```ufal.gen.out```generates 7 files, namely:

- ```ref.ufal.0X``` (X = 1, 2, 3)
- ```hyp.ufal.oY``` (Y = 1, 2)
- ```ufal-test.hyp```
- ```ufal-test.ref```


When you say 
> don't use the generated references.....use references from the original test-set

I interpret this to mean that instead of running the command
```
python3 -m indicnlp.contrib.wat.evaluate \
        --reference ref.ufal.00 --hypothesis hyp.ufal.00 
``` 
I run the following command?

```
python3 -m indicnlp.contrib.wat.evaluate \
        --reference ufal-test.ref --hypothesis ufal-test.hyp 
```

**Comment by jerinphilip** [comment]
No, anything that comes out of fairseq generate will have loss. Some tokens might be missing.

In the release of the dev and test sets corresponding to the UFAL task/dataset, you can find a test.ta and test.en. Use that for --references. Not an output that is generated starting from fairseq-generate.

**Comment by alphadoretto** [comment]
Yeah got it, thanks
